l3_interfaces:
- ethernet3
- ethernet4

interfaces:
- {interface: "ethernet3", ip: "10.1.1.1/31"}
- {interface: "ethernet4", ip: "10.1.2.1/31"}
- {interface: "loopback0", ip: "1.1.1.1/32"}
- {interface: "loopback1", ip: "12.12.12.12/32"}