l3_interfaces:
- ethernet5
- ethernet6

ip_interfaces:
- { interface: "ethernet3", ip: "10.4.1.1/31" }
- { interface: "ethernet4", ip: "10.4.2.1/31" }
- { interface: "ethernet5", ip: "10.4.3.1/31" }
- { interface: "ethernet6", ip: "10.4.4.1/31" }
- { interface: "loopback0", ip: "4.4.4.4/32" }

local_asn: 65004

bgp_neighbors:
- { peer_ip: 10.4.1.0, asn: 65101 }
- { peer_ip: 10.4.2.0, asn: 65101 }
- { peer_ip: 10.4.3.0, asn: 65101 }
- { peer_ip: 10.4.4.0, asn: 65101 }