l3_interfaces:
- ethernet3
- ethernet4
- ethernet5
- ethernet6

ip_interfaces:
- { interface: "ethernet3", ip: "10.1.1.1/31" }
- { interface: "ethernet4", ip: "10.1.2.1/31" }
- { interface: "ethernet5", ip: "10.1.3.1/31" }
- { interface: "ethernet6", ip: "10.1.4.1/31" }
- { interface: "loopback0", ip: "1.1.1.1/32" }
- { interface: "loopback1", ip: "121.121.121.121/32" }


local_asn: 65001

bgp_neighbors:
- { peer_ip: 10.1.1.0, asn: 65101 }
- { peer_ip: 10.1.2.0, asn: 65101 }
- { peer_ip: 10.1.3.0, asn: 65101 }
- { peer_ip: 10.1.4.0, asn: 65101 }