l3_interfaces:
- ethernet3
- ethernet4

ip_interfaces:
- {interface: "ethernet3", ip: "10.2.1.1/31"}
- {interface: "ethernet4", ip: "10.2.2.1/31"}
- {interface: "loopback0", ip: "2.2.2.2/32"}
- {interface: "loopback1", ip: "12.12.12.12/32"}