l3_interfaces:
- ethernet3
- ethernet4
- ethernet5
- ethernet6

ip_interfaces:
- { interface: "ethernet3", ip: "10.2.1.1/31" }
- { interface: "ethernet4", ip: "10.2.2.1/31" }
- { interface: "ethernet5", ip: "10.2.3.1/31" }
- { interface: "ethernet6", ip: "10.2.4.1/31" }
- { interface: "loopback0", ip: "2.2.2.2/32" }
- { interface: "loopback1", ip: "121.121.121.121/32" }

local_asn: 65002

bgp_neighbors:
- { peer_ip: 10.2.1.0, asn: 65101 }
- { peer_ip: 10.2.2.0, asn: 65101 }
- { peer_ip: 10.2.3.0, asn: 65101 }
- { peer_ip: 10.2.4.0, asn: 65101 }