---
- name: Provision BGP
  hosts: all
  gather_facts: no
  tasks:

  - name: Get IP address of Loopback 0
    arista.eos.eos_command:
      commands:
        - command: show ip interface loopback0
          output: json
    register: loopback0

  - name: Print Loopback0 IP Address
    ansible.builtin.debug: 
      var: loopback0

  - name: enable IP routing
    arista.eos.eos_config:
      lines: ip routing

  - name: Configure basic BGP peering
    arista.eos.eos_bgp_global:
      config:
        as_number: "{{ local_asn }}"
        maximum_paths:
          max_equal_cost_paths: 4
        redistribute:
          - protocol: "connected"
        neighbor:
          - peer: "{{ item.peer_ip }}"
            remote_as: "{{ item.asn }}"
    loop: "{{ bgp_neighbors }}"