---
- name: Provision BGP
  hosts: all
  gather_facts: no
  tasks:

  - name: enable IP routing
    arista.eos.eos_config:
      lines: ip routing

  - name: Configure basic BGP peering
    arista.eos.eos_bgp_global:
      config:
        as_number: "{{ local_asn }}"
        maximum_paths:
          max_equal_cost_paths: 4
        redistribute:
          - protocol: "connected"
        neighbor:
          - peer: "{{ item.peer_ip }}"
            remote_as: "{{ item.asn }}"
    loop: "{{ bgp_neighbors }}"