---
- name: Provision BGP
  hosts: switches
  gather_facts: no
  tasks:

  - name: Get IP address of Loopback0
    arista.eos.eos_command:
      commands:
        - command: show ip interface loopback0
          output: json
    register: loopback0

  - name: enable IP routing
    arista.eos.eos_config:
      lines: ip routing

  - name: Configure basic BGP peering
    arista.eos.eos_bgp_global:
      config:
        as_number: "{{ local_asn }}"
        router_id: "{{ loopback0.stdout[0].interfaces.Loopback0.interfaceAddress.primaryIp.address }}"
        maximum_paths:
          max_equal_cost_paths: 4
        bgp_params:
          log_neighbor_changes: true
        redistribute:
          - protocol: "connected"
        neighbor:
          - peer: "{{ item.peer_ip }}"
            remote_as: "{{ item.asn }}"
    loop: "{{ bgp_neighbors }}"