---
- name: Provision EOS interfaces
  hosts: all
  gather_facts: no
  tasks:

  - name: Configure L3 Interfaces
    arista.eos.eos_interfaces:
      config:
        - name: "{{ item }}"
          enabled: true
          mode: layer3
    loop: "{{ l3_interfaces }}"

  - name: Assign IP addresses to L3 Interfaces
    arista.eos.eos_l3_interfaces:
      config:
        - name: "{{ item.interface }}"
          ipv4:
            - address: "{{ item.ip }}"
    loop: "{{ ip_interfaces }}"