---
- name: Verify VXLAN EVPN state
  hosts: servers
  gather_facts: no
  tasks:

  - name: Ping host IPs across VXLAN overlay
    arista.eos.eos_command:
      commands:
        - command: "ping {{ item }}"
          output: text
    register: ping
    loop:
      "{{ host_ips }}"

  - name: Print results of ping
    ansible.builtin.debug:
      var: ping
  
  - name: Check BGP EVPN tables
    arista.eos.eos_command:
      commands:
        - command: "show bgp evpn"
    register: bgp
  
  - name: Print BGP EVPN tables
    ansible.builtin.debug:
      var: bgp